# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: route_engine.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'route_engine.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12route_engine.proto\x12\x0croute_engine\"&\n\nCoordinate\x12\x0b\n\x03lat\x18\x01 \x01(\x01\x12\x0b\n\x03lng\x18\x02 \x01(\x01\"?\n\tNodeProto\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0b\n\x03lat\x18\x02 \x01(\x01\x12\x0b\n\x03lng\x18\x03 \x01(\x01\x12\x0c\n\x04name\x18\x04 \x01(\t\"Y\n\tEdgeProto\x12\t\n\x01u\x18\x01 \x01(\x05\x12\t\n\x01v\x18\x02 \x01(\x05\x12\x10\n\x08weight_m\x18\x03 \x01(\x01\x12\x11\n\tspeed_kmh\x18\x04 \x01(\x05\x12\x11\n\troad_type\x18\x05 \x01(\t\"\\\n\nMapPayload\x12&\n\x05nodes\x18\x01 \x03(\x0b\x32\x17.route_engine.NodeProto\x12&\n\x05\x65\x64ges\x18\x02 \x03(\x0b\x32\x17.route_engine.EdgeProto\"\xd7\x01\n\x0cRouteRequest\x12\'\n\x05start\x18\x01 \x01(\x0b\x32\x18.route_engine.Coordinate\x12%\n\x03\x65nd\x18\x02 \x01(\x0b\x32\x18.route_engine.Coordinate\x12\x11\n\tmock_hour\x18\x03 \x01(\x05\x12*\n\tobjective\x18\x04 \x01(\x0e\x32\x17.route_engine.Objective\x12\x10\n\x08map_data\x18\x05 \x01(\t\x12\x11\n\tregion_id\x18\x06 \x01(\t\x12\x13\n\x0bmap_data_pb\x18\x07 \x01(\x0c\"\xec\x01\n\x0f\x41lgorithmResult\x12\x11\n\talgorithm\x18\x01 \x01(\t\x12*\n\x08polyline\x18\x02 \x03(\x0b\x32\x18.route_engine.Coordinate\x12\x10\n\x08\x64istance\x18\x03 \x01(\x01\x12\x10\n\x08\x64uration\x18\x04 \x01(\x01\x12\x16\n\x0enodes_expanded\x18\x05 \x01(\x05\x12\x14\n\x0c\x65xec_time_ms\x18\x06 \x01(\x01\x12\x11\n\tpath_cost\x18\x07 \x01(\x01\x12\x12\n\ndebug_logs\x18\x08 \x01(\t\x12!\n\x19\x63ircuit_breaker_triggered\x18\t \x01(\x08\"?\n\rRouteResponse\x12.\n\x07results\x18\x01 \x03(\x0b\x32\x1d.route_engine.AlgorithmResult*&\n\tObjective\x12\x0b\n\x07\x46\x41STEST\x10\x00\x12\x0c\n\x08SHORTEST\x10\x01\x32[\n\x0cRouteService\x12K\n\x0e\x43\x61lculateRoute\x12\x1a.route_engine.RouteRequest\x1a\x1b.route_engine.RouteResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'route_engine_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OBJECTIVE']._serialized_start=848
  _globals['_OBJECTIVE']._serialized_end=886
  _globals['_COORDINATE']._serialized_start=36
  _globals['_COORDINATE']._serialized_end=74
  _globals['_NODEPROTO']._serialized_start=76
  _globals['_NODEPROTO']._serialized_end=139
  _globals['_EDGEPROTO']._serialized_start=141
  _globals['_EDGEPROTO']._serialized_end=230
  _globals['_MAPPAYLOAD']._serialized_start=232
  _globals['_MAPPAYLOAD']._serialized_end=324
  _globals['_ROUTEREQUEST']._serialized_start=327
  _globals['_ROUTEREQUEST']._serialized_end=542
  _globals['_ALGORITHMRESULT']._serialized_start=545
  _globals['_ALGORITHMRESULT']._serialized_end=781
  _globals['_ROUTERESPONSE']._serialized_start=783
  _globals['_ROUTERESPONSE']._serialized_end=846
  _globals['_ROUTESERVICE']._serialized_start=888
  _globals['_ROUTESERVICE']._serialized_end=979
# @@protoc_insertion_point(module_scope)
