# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: route_engine.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'route_engine.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12route_engine.proto\x12\x0croute_engine\"&\n\nCoordinate\x12\x0b\n\x03lat\x18\x01 \x01(\x01\x12\x0b\n\x03lng\x18\x02 \x01(\x01\"\xaf\x01\n\x0cRouteRequest\x12\'\n\x05start\x18\x01 \x01(\x0b\x32\x18.route_engine.Coordinate\x12%\n\x03\x65nd\x18\x02 \x01(\x0b\x32\x18.route_engine.Coordinate\x12\x11\n\tmock_hour\x18\x03 \x01(\x05\x12*\n\tobjective\x18\x04 \x01(\x0e\x32\x17.route_engine.Objective\x12\x10\n\x08map_data\x18\x05 \x01(\t\"\xb5\x01\n\x0f\x41lgorithmResult\x12\x11\n\talgorithm\x18\x01 \x01(\t\x12*\n\x08polyline\x18\x02 \x03(\x0b\x32\x18.route_engine.Coordinate\x12\x10\n\x08\x64istance\x18\x03 \x01(\x01\x12\x10\n\x08\x64uration\x18\x04 \x01(\x01\x12\x16\n\x0enodes_expanded\x18\x05 \x01(\x05\x12\x14\n\x0c\x65xec_time_ms\x18\x06 \x01(\x01\x12\x11\n\tpath_cost\x18\x07 \x01(\x01\"?\n\rRouteResponse\x12.\n\x07results\x18\x01 \x03(\x0b\x32\x1d.route_engine.AlgorithmResult*&\n\tObjective\x12\x0b\n\x07\x46\x41STEST\x10\x00\x12\x0c\n\x08SHORTEST\x10\x01\x32[\n\x0cRouteService\x12K\n\x0e\x43\x61lculateRoute\x12\x1a.route_engine.RouteRequest\x1a\x1b.route_engine.RouteResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'route_engine_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OBJECTIVE']._serialized_start=503
  _globals['_OBJECTIVE']._serialized_end=541
  _globals['_COORDINATE']._serialized_start=36
  _globals['_COORDINATE']._serialized_end=74
  _globals['_ROUTEREQUEST']._serialized_start=77
  _globals['_ROUTEREQUEST']._serialized_end=252
  _globals['_ALGORITHMRESULT']._serialized_start=255
  _globals['_ALGORITHMRESULT']._serialized_end=436
  _globals['_ROUTERESPONSE']._serialized_start=438
  _globals['_ROUTERESPONSE']._serialized_end=501
  _globals['_ROUTESERVICE']._serialized_start=543
  _globals['_ROUTESERVICE']._serialized_end=634
# @@protoc_insertion_point(module_scope)
